### ISSUE TITLE
sed: -e expression #1, char 1: missing command

### ISSUE THREAD

**Issue by ThomasH-W** [Red5d/pushbullet-bash#84]
Red5d, thanks for providing this tool. It looks like you spend squite some time on it.

In my case the connection is successfully established but when sending a note the error message is returned.

[14:16:40] openhabian@openHABianPi:~/pushbullet-bash$ ./pushbullet list
Available devices:
------------------
Babel Fish
Babel Fish
iPad von Thomas
iPad von Thomas
PHOENIX-8
all

Chats/Contacts:
------------------
# a simple failure test
$ ./pushbullet  push "Babel dummy" note "dummy"
Sending to channel Babel dummy
Error: You specified an unknown device or channel.

 ./pushbullet  push "Babel Fish" note "dummy"
sed: -e expression #1, char 1: missing command

**Comment by fbartels** [comment]
Hi @ThomasH-W ,

thanks for you report. the culprit here seems to be that your devices are duplicated and the script therefore cannot find a unique match for "Babel Fish" (i was able to reproduce this here locally).

**Comment by ThomasH-W** [comment]
Thanks for the quick reply. I was expected this when looking at the pushbullet list.
Nevertheless when checking the settings of my accoutn at pushbullet.com, I do not see the double entries.
I got a new mobile phone and assigned the same name. Probably pushbullet.com cannot handle this.

**Comment by fbartels** [comment]
Hi @ThomasH-W ,

i refined my approach a bit and instead of blindly taking the first result the code now gives an error message. I by the way see the same result as you, reinstalled a device a few times and now it gets listed three times in `pushbullet list`, but still only once in the webinterface. I never push to that device from the cli so never noticed the mistake.

Maybe an additional function to delete devices from the cli could be helpful here?
